### ISSUE TITLE
[Question] Change default icon of application

### ISSUE THREAD

**Issue by Ouri028** [ttytm/webview#23]
Hey,

So, first off great job with the bindings so far.

I had a question, I was successful in changing the default application icon and was wondering if this was something that you might like to add?

Currently it only works on Windows as it uses the Windows API to change the resource of the icon.

Here is a simple example.
It is using a 512x512 .ico file.

![image](https://github.com/ttytm/webview/assets/49057553/5a7dde96-6d82-4666-9594-2ba4e52deee8)

Please let me know if you would like for me to integrate this into the current bindings and potentially support Linux and MacOS at a later stage?

**Comment by ttytm** [comment]
Hey @Ouri028, thanks for reaching out. Are you using vwebui or webview? They are similar libraries I maintain 🙂

The dark Icon on dark titlebars has to little contrast, on a light titlebar (if there are people who are using it 😜) it would be to dark I assume. I an ico from the regular V logo https://github.com/vlang/v-logo would be just fine. It works on both surfaces. What do you think?

**Comment by Ouri028** [comment]
I am using webview (I just made the title that 😄 ), I also used a darker icon I received from https://icon-icons.com as a test, to be precise this icon https://icon-icons.com/icon/V/131906.

Here is an example using the default V lang logo.

The size and quality is dependent on the .ico file.

![image](https://github.com/ttytm/webview/assets/49057553/89580dab-9d87-4654-aa25-1fa4437d0e6c)

**Comment by ttytm** [comment]
Yes that's fine for a default icon. 

I'd love to know how you integrated it and see where it fits in the lib. So a PR is welcome :+1:

**Comment by Ouri028** [comment]
Awesome, will create a PR a little later today 😎

**Comment by Ouri028** [comment]
Pull request opened.
